name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java: [11, 17]
    name: Java ${{ matrix.java }} sample

    steps:
    - name: Checkout calimero-core
      uses: actions/checkout@v2
      with:
        repository: calimero-project/calimero-core
        path: calimero-core
    - name: Checkout calimero-rxtx
      uses: actions/checkout@v2
      with:
        repository: calimero-project/calimero-rxtx
        path: calimero-rxtx
    - name: Checkout calimero-usb
      uses: actions/checkout@v2
      with:
        repository: calimero-project/calimero-usb
        path: calimero-usb
    - name: Checkout calimero-tools
      uses: actions/checkout@v2
      with:
        path: calimero-tools
    - name: setup
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Grant execute permission for gradlew
      run: |
        cd calimero-tools
        chmod +x gradlew
    - name: Build with Gradle
      run: |
        cd calimero-tools
        ./gradlew build
